---
title: "Clustering Top Economists"
author: "Junsok Huhh"
date: '2017-12-17'
tags: ['R', 'economics', 'economist', 'clustering']
categories: ['data', 'clustering']
output: 
  html_document: 
    df_print: kable
---

# Disclaimer 

```{r include=FALSE}
library(tidyverse)
library(knitr)
library(wrapr)
library(ggthemes) 
library(showtext)
library(here)
library(printr)
library(kableExtra)
load("data/eda.RData") 

#font_add("square", regular = "fonts/NanumSquareR.otf")
```

# Motivation 

집에 심심하게 있다가 갑자기 이런 생각이 떠올랐다. 믿을만한 경제학자들은 얼마나 의견에 합의를 볼 수 있을까? 그 믿을만한 경제학자들이 우수한 학자들이면 더 좋을 것이다. 여기에 생각이 미치자, '데이터는 어디서 구하지'라고 생각이 흘렀고, 당장 시카고 Booth의 IGM을 떠올렸다. IGM이 그간 몇 개의 토픽을 다뤘는지 가보니 사례는 충분했다. 이제 기술적인 문제다. 웹 자료니까 긁어야하는데 웹스크래핑을 해본지 꽤 되었다. Python에서만 해봤는데, R에서도 해보면 좀 도움이 될까 싶었다. 마지막으로 자료의 성격이 문제다. 보니, 전형적인 리커드 자료(Likert scale), 즉 5점 척도다. 흠, 얘네들을 클러스터링 하려면 어떻게 해야 하나? 일단, 양적 자료는 아니니 K-means 같은 표준적이고 쉬운 방법은 열외다. 리커트 자료를 다루는 데는 문외한이고 이제부터 공부해서 뭔가 만들어낼 성의는 없다. 딱 주말에 심심풀이로 꺼내든 프로젝트라서 주말에 끝내고 싶었다! (역시 나에게는 대충과 야매가 어울린다.)

이 글은 이러한 주말의 의식을 흐름을 따르는 형식으로 작성해보도록 하자. 

  1. 우선 IGM 사이트의 웹을 긁어오기 
  2. 자료 정리 및 클러스터링 적용하기 
  3. 결과에 대한 내만대로 해석 혹은 해설 
  
# How to scrap results of IGM panel  

웹을 스크래핑 하는 데에는 몇 가지 방법이 있지만 기술적인 내용을 제외하고 실용적으로 보자면 코드로 하느냐 아니면 수작업으로 하느냐 둘 중 하나다. 후자는 다시 '정말' 손으로 하는지 아니면 '손'을 흉내내는지에로 다시 가를 수 있다. 코드로 하는게 가장 좋겠지만 이건 진입장벽이 있고, js로 된 사이트들은 더 많이 고민해야 한다. 경우에 따라서는 후자가 빠를 수도 있으니 굳이 노가다하는 걸 망설일 필요는 없겠다. 게다가, 시중에서 흔히 볼 수 있는 매크로 프로그램들을 잘 쓰면 생각보다 쉽게 데이터를 얻을 수 있다. 

어쨌든 웹 스크래핑은 파이썬의 장점이었지만, RStudio에서 내놓은 rvest 패키지 떄문에 이런 격차를 순식간에 사라지게 된 것 같다. 웹사이트를 html로 저장한 뒤 node를 따는 방식으로 원하는 자료들을 쉽게 긁을 수 있다. 다만, 이 경우 웹사이트를 뭔가 숨겨놓지 않아야 하는데 IGM의 경우에는 구조를 그대로 볼 수 있게 되어 있다. 

이런 방식으로 IGM 사이트를 두 개를 각각 따로따로 긁어냈다. 하나는 경제학자들에게 질문을 던진 토픽을 긁어냈고 그 토픽에 대한 경제학자들의 답 내용을 긁어냈다. 토픽은 2017년 12월 17일 현재 전부 158개였으나, 패널은 51명의 저명한 경제학자들로 구성되어 있다. 이 중 금융위기에 관한 질문은 나머지와 다른 구조를 갖고 있으므로 제외했다. 따라서 분석에 활용된 토픽은 157개다. 

# How to group economists 

클러스터링이랑 관찰이 지닌 속성(변수)을 비교해 비슷한 무리를 묶는 통계적 기법이다. 이때 비슷한 무리를 묶기 위해 필요한 것은 거리 개념이다. 그래서 양적 변수를 지닌 대상들에 쉽게 적용되고, 가장 표준적인 클러스터링 방법은 k-menas다. 그런데 우리 자료는 양적 자료가 아니다. 이를 억지로 양적 자료로 만들어 쓸 수 있겠지만 응답과 응답 사이에 인터벌 개념을 임의로 가정하지 않는 이상 자의성을 띨 수 밖에 없다. k-means를 쓸 수 없다면 다음으로 생각해 볼 수 있는 방법이 계층 클러스터링(hierarchical clustering, 이하 HC)이다. 말이 그대로 시사하듯이 전체 하나가 전부 다르다고 가정한 후 비슷한 관찰을 묶는 방법(bottom-up) 혹은 전체가 전부 하나의 군집이라고 가정한 후 가지를 쳐 나가는 방법(top-down), 두 가지가 있다.    

HC는 IGM 패널과 같은 양적 혹은 범주 자료를 다루기에도 비교적 적합하다. 물론 k-means 만큼 명쾌하지 않을 수는 있지만, 언제나 그렇듯이 방법이 없는 것보다는 낫지 않겠는가? 두 방법 모두 R에서 지원한다. 

# How different are economist? 

위 얻은 HC 집단에 대해서 각 설문별로 중위값을 취해 그룹의 '대표 견해'라고 가정해보자. 그룹 사이에 대표 견해에 큰 차이가 있을까? 결과를 보시면 알겠지만, 미국의 저명한 경제학자들은 다른 면보다는 비슷한 면이 많다. 이에 대한 해석은 알아서 각자 하시면 되겠다. 다소 의견 대립이 있지 않을까, 이왕이면 '좌우'로 나눠서 싸워주면 좋지 않을까 했던 개인적인 바람이 있었지만... 

앞서 세개의 집단으로 나눈 경제학들의 특성 정도는 볼 수 있겠다.  

  1. 1번 집단은 적극적으로 활발한 의견을 개진힌 집단이다. 즉 참여하지 않는 설문이 가장 낮은 집단이기도 하다. 
  2. 2번 집단은 가장 소극적으로 의견을 개진한 집단이다. 
  3. 3번 1번의 중간 정도의 의견 개진을 한 집단이다. 
  
HC를 적용하는 과정에서 무응답은 "uncertain"으로 처리했다. 이렇게 가정하면, 1과 2 그리고 1와 3 사이에 완전 의견 일치를 보는 토픽은 100개가 넘는다. 2와 3 사이의 성향이 달라서 완전히 동의한 토픽은 50개 정도다. 

응답의 방향성이 지닌 차이는 있을까? 답변이 리커트 자료이기 때문에 의견일치를 보지 못하는 토픽을 쉽게 찾을 수 있다. 즉, 3번 "uncertain"을 기준으로 이 경계를 넘는 차이가 존재했는지 찾아볼 수 있다. 즉, 한 집단은 "Strongly Agree" 혹은 "Agree"가 대표값인 질문이 있을 때 다른 집단은 "Disagree" 혹은 "Strongly Disagree"가 대표값인 경우가 있는지를 찾으면 된다. 이런 경우는 딱 5개의 질문 밖에 없었다. 즉, IGM 패널의 경제학자들의 경우 한 집단의 견해에 대해서 찬반 내에서 함께 움직이는 경우가 많으며 많이 움직여야 "uncertain"까지 이동했다고 볼 수 있겠다. 

# One more things 

더 해볼 수 있는 걸 생각해볼까? (내가 하겠다는 건 아니다...)

  1. 이 경제학자들의 추가 변수를 구한다면 뭔가 더 해 볼 수 있겠다. 전공 분야, 대학, 논문 수 등등 
  2. 몇가지 시도해 볼만한 추가적인 클러스터링 기법이 더 있긴 하다. 
  3. 나보다 더 훌륭한 분들이 많으니 자료를 퍼가서 마음껏 활용하시라, 마! 
  

  
